development:
  adapter: postgresql
  database: lhcmocks_development
  pool: 5
  timeout: 5000
  host: localhost
  #username: postgres
  #password: 19loki76
  username: postgres
  password: p20o20e13

test:
  adapter: postgresql
  database: lhcmocks_test
  pool: 5
  timeout: 5000
  host: localhost
  #username: postgres
  #password: 19loki76
  username: postgres
  password: p20o20e13

production:
  adapter: postgresql
  database: lhcmocks_production
  pool: 5
  timeout: 5000
  host: localhost
  #username: postgres
  #password: 19loki76
  username: postgres
  password: p20o20e13
