development:
  adapter: postgresql
  database: lhcmocks_development
  pool: 5
  timeout: 5000
  username: postgres
  host: localhost
  password: 19loki76


test:
  adapter: postgresql
  database: lhcmocks_test
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  password: 19loki76

production:
  adapter: postgresql
  database: lhcmocks_production
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  password: 19loki76
