development:
  adapter: postgresql
  database: lhcmocks_development
  pool: 5
  timeout: 5000
  username: postgres
  password: 19loki76
#  username: nilesh
#  password: p20o20e13

test:
  adapter: postgresql
  database: lhcmocks_test
  pool: 5
  timeout: 5000
  username: postgres
  password: 19loki76
#  username: nilesh
#  password: p20o20e13

production:
  adapter: postgresql
  database: lhcmocks_production
  pool: 5
  timeout: 5000
  username: postgres
  password: 19loki76
#  username: nilesh
#  password: p20o20e13


#sudo -u postgres psql postgres -> as user postgres
#psql -d lhcmocks_development -U nilesh -W

#TODO: Change username & pwd before pushing on server